apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: pythonapp
